version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8877:80"
        depends_on:
            - db
        container_name: phonebook_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: phonebook_app



    db:
        image: mysql:latest
        container_name: phonebook_db
        restart: always
        environment:
            MYSQL_DATABASE: phonebook
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8102:3306"
